name: release
on:
  push:
    branches:
    - dev

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install SSH Client
      continue-on-error: true
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.MY_ACTIONS_DEPLOY_KEY  }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Build
      run: |
        make html

    - name: Build And Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        SSH: true
        BRANCH: master
        FOLDER: docs
