name: reviewdog

on:
  pull_request:
    branched: [ dev ]

# Ref
# * https://zenn.dev/yuta28/articles/blog-lint-ci-reviewdog

jobs:
  reviewdog-github-check:
    name: reviewdog (github check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Execute textlint of github PR review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "source/contents/**/*.md"

