name: reviewdog

on:
  pull_request:
    branched: [ dev ]

# Ref
# * https://zenn.dev/yuta28/articles/blog-lint-ci-reviewdog

jobs:
  reviewdog-github-check:
    name: reviewdog (github check)
    runs-on: ubuntu-latest

    steps:
      # action of reviewdog
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # node action to run textlint
      - uses: actions/setup-node@v2
      
      - uses: actions/checkout@v2

      - name: Execute textlint of github PR review
        with:
          github_token: ${{ secrets.github_token }}
          reporter: guthub-pr-review
          level: warning
          textlint_flags: "source/contents/**/*.md"

